
CREATE TABLE Airports (
    AirportCode VARCHAR2(3) PRIMARY KEY,
    AirportName VARCHAR2(100) NOT NULL,
    City VARCHAR2(50) NOT NULL,
    Country VARCHAR2(50) NOT NULL
);

CREATE INDEX idx_airports_city ON Airports(City);

CREATE TABLE Aircraft (
    AircraftID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Model VARCHAR2(50) NOT NULL,
    TailNumber VARCHAR2(20) NOT NULL UNIQUE,
    TotalSeats NUMBER(10) NOT NULL,
    ManufactureYear NUMBER(4)
);

CREATE TABLE Users (
    UserID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    Role VARCHAR2(20) DEFAULT 'Passenger' 
        CHECK (Role IN ('Admin', 'Staff', 'Passenger')),
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_users_role ON Users(Role);

CREATE TABLE Passengers (
    PassengerID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER(10) UNIQUE,
    PassportNumber VARCHAR2(20) NOT NULL UNIQUE,
    Nationality VARCHAR2(50),
    PhoneNumber VARCHAR2(20),
    FrequentFlyerNumber VARCHAR2(50) UNIQUE,
    CONSTRAINT fk_passengers_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL
);

CREATE TABLE Flights (
    FlightID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FlightNumber VARCHAR2(10) NOT NULL UNIQUE,
    AircraftID NUMBER(10) NOT NULL,
    DepartureAirport VARCHAR2(3) NOT NULL,
    ArrivalAirport VARCHAR2(3) NOT NULL,
    DepartureTime TIMESTAMP NOT NULL,
    ArrivalTime TIMESTAMP NOT NULL,
    BasePrice NUMBER(10,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Scheduled' 
        CHECK (Status IN ('Scheduled', 'Delayed', 'Departed', 'Arrived', 'Cancelled')),
    CONSTRAINT fk_flights_aircraft 
        FOREIGN KEY (AircraftID) REFERENCES Aircraft(AircraftID),
    CONSTRAINT fk_flights_departure_airport 
        FOREIGN KEY (DepartureAirport) REFERENCES Airports(AirportCode),
    CONSTRAINT fk_flights_arrival_airport 
        FOREIGN KEY (ArrivalAirport) REFERENCES Airports(AirportCode)
);

CREATE INDEX idx_flights_aircraft ON Flights(AircraftID);
CREATE INDEX idx_flights_departure_time ON Flights(DepartureTime);
CREATE INDEX idx_flights_status ON Flights(Status);

CREATE TABLE AircraftSeats (
    SeatID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AircraftID NUMBER(10) NOT NULL,
    SeatNumber VARCHAR2(5) NOT NULL,
    Class VARCHAR2(20) NOT NULL 
        CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First')),
    Status VARCHAR2(20) DEFAULT 'AVAILABLE' 
        CHECK (Status IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE')),
    CONSTRAINT fk_aircraftseats_aircraft 
        FOREIGN KEY (AircraftID) REFERENCES Aircraft(AircraftID) ON DELETE CASCADE,
    CONSTRAINT uk_aircraftseats_seat 
        UNIQUE (AircraftID, SeatNumber)
);

CREATE INDEX idx_aircraftseats_aircraft ON AircraftSeats(AircraftID);
CREATE INDEX idx_aircraftseats_status ON AircraftSeats(Status);

CREATE TABLE Bookings (
    BookingID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingReference VARCHAR2(6) NOT NULL UNIQUE,
    UserID NUMBER(10),
    BookingDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'Pending' 
        CHECK (Status IN ('Confirmed', 'Pending', 'Cancelled')),
    CONSTRAINT fk_bookings_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE INDEX idx_bookings_userid ON Bookings(UserID);
CREATE INDEX idx_bookings_status ON Bookings(Status);

CREATE TABLE Tickets (
    TicketID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER(10) NOT NULL,
    FlightID NUMBER(10) NOT NULL,
    PassengerID NUMBER(10) NOT NULL,
    SeatNumber VARCHAR2(5) NOT NULL,
    Class VARCHAR2(20) NOT NULL 
        CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First')),
    TicketPrice NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_tickets_booking 
        FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID) ON DELETE CASCADE,
    CONSTRAINT fk_tickets_flight 
        FOREIGN KEY (FlightID) REFERENCES Flights(FlightID),
    CONSTRAINT fk_tickets_passenger 
        FOREIGN KEY (PassengerID) REFERENCES Passengers(PassengerID),
    CONSTRAINT uk_tickets_seat 
        UNIQUE (FlightID, SeatNumber)
);

CREATE INDEX idx_tickets_booking ON Tickets(BookingID);
CREATE INDEX idx_tickets_flight ON Tickets(FlightID);
CREATE INDEX idx_tickets_passenger ON Tickets(PassengerID);

CREATE TABLE Payments (
    PaymentID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER(10) NOT NULL,
    Amount NUMBER(10,2) NOT NULL,
    PaymentDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    PaymentMethod VARCHAR2(20) NOT NULL 
        CHECK (PaymentMethod IN ('Credit Card', 'Debit Card', 'PayPal', 'Stripe', 'UPI', 'Net Banking')),
    TransactionStatus VARCHAR2(20) NOT NULL 
        CHECK (TransactionStatus IN ('Success', 'Failed', 'Refunded')),
    TransactionReference VARCHAR2(100) UNIQUE,
    CONSTRAINT fk_payments_booking 
        FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID)
);

CREATE INDEX idx_payments_booking ON Payments(BookingID);
CREATE INDEX idx_payments_status ON Payments(TransactionStatus);

CREATE TABLE UserSessions (
    SessionID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER(10) NOT NULL,
    RefreshToken VARCHAR2(500) NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_usersessions_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE INDEX idx_usersessions_userid ON UserSessions(UserID);

CREATE TABLE CrewAssignment (
    AssignmentID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FlightID NUMBER(10) NOT NULL,
    UserID NUMBER(10) NOT NULL,
    CrewRole VARCHAR2(50) NOT NULL 
        CHECK (CrewRole IN ('Pilot', 'Co-Pilot', 'Cabin Crew Lead', 'Cabin Crew')),
    CONSTRAINT fk_crewassignment_flight 
        FOREIGN KEY (FlightID) REFERENCES Flights(FlightID) ON DELETE CASCADE,
    CONSTRAINT fk_crewassignment_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE INDEX idx_crewassignment_flight ON CrewAssignment(FlightID);
CREATE INDEX idx_crewassignment_user ON CrewAssignment(UserID);

CREATE TABLE Baggage (
    BaggageID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketID NUMBER(10) NOT NULL,
    WeightKG NUMBER(5,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Checked-In' 
        CHECK (Status IN ('Checked-In', 'In-Transit', 'On-Plane', 'Ready-for-Pickup', 'Lost')),
    TrackingNumber VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT fk_baggage_ticket 
        FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID) ON DELETE CASCADE
);

CREATE INDEX idx_baggage_ticket ON Baggage(TicketID);
CREATE INDEX idx_baggage_status ON Baggage(Status);

-- Performance & Composite Indexes
CREATE INDEX idx_flights_search ON Flights(DepartureAirport, ArrivalAirport, DepartureTime, Status);
CREATE INDEX idx_seats_aircraft_class ON AircraftSeats(AircraftID, Class, Status);
CREATE INDEX idx_bookings_date ON Bookings(BookingDate);
CREATE INDEX idx_payments_booking_status ON Payments(BookingID, TransactionStatus);
CREATE INDEX idx_airports_name ON Airports(AirportName);

-- ============================================
-- STAFF REGISTRY TABLE
-- Admins create Staff IDs here. Staff members
-- use these IDs during registration to get
-- the 'Staff' role assigned to their account.
-- ============================================

CREATE TABLE StaffRegistry (
    StaffID VARCHAR2(20) PRIMARY KEY,
    IsAssigned NUMBER(1) DEFAULT 0 NOT NULL,
    AssignedUserID NUMBER(10),

    CONSTRAINT chk_staff_assigned
        CHECK (IsAssigned IN (0, 1)),

    CONSTRAINT fk_staff_assigned_user
        FOREIGN KEY (AssignedUserID)
        REFERENCES Users(UserID)
);

CREATE INDEX idx_staffregistry_assigned ON StaffRegistry(IsAssigned);
CREATE INDEX idx_staffregistry_userid ON StaffRegistry(AssignedUserID);

-- ============================================
-- FEEDBACK TABLE
-- ============================================

CREATE TABLE Feedback (
    FeedbackID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100),
    Email VARCHAR2(100),
    Category VARCHAR2(100) NOT NULL,
    Rating NUMBER(1) DEFAULT 5 CHECK (Rating BETWEEN 1 AND 5),
    Message VARCHAR2(4000) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_feedback_createdat ON Feedback(CreatedAt);

-- ============================================
-- IDENTITY SEQUENCE RESET
-- ============================================
-- If you have previously run this schema and want to reset
-- identity counters back to 1, run these BEFORE inserting
-- any data. These only work on empty tables.
--
-- ALTER TABLE Users MODIFY (UserID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Passengers MODIFY (PassengerID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Aircraft MODIFY (AircraftID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Flights MODIFY (FlightID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE AircraftSeats MODIFY (SeatID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Bookings MODIFY (BookingID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Tickets MODIFY (TicketID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Payments MODIFY (PaymentID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE UserSessions MODIFY (SessionID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE CrewAssignment MODIFY (AssignmentID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
-- ALTER TABLE Baggage MODIFY (BaggageID GENERATED BY DEFAULT AS IDENTITY (START WITH 1));

-- ============================================
-- ADMIN USERS (database-seeded only)
-- These are the only pre-seeded records.
-- All other data comes from seed.sql
-- ============================================

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role)
VALUES ('Tanmay', 'Gurav', 'tanmaygurav2326@gmail.com',
        '$2b$10$HI3W27om.zpYC5c1dljZveWFmGnD.oDccs9ISstU.Gxd6XLiibpgK', 'Admin');

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role)
VALUES ('Lokesh', 'Sonowane', 'lokeshsonowane2009@gmail.com',
        '$2b$10$rl8hmj9LfA0MAF0mhuGD1.7WdOZ9AW/2fr5dhucWpNy6j.ce3h6wK', 'Admin');

COMMIT;

-- Verification query (optional — run to confirm admin users exist)
SELECT 'Users' as TableName, COUNT(*) as RecordCount FROM Users
UNION ALL
SELECT 'StaffRegistry', COUNT(*) FROM StaffRegistry;